// <auto-generated />
using System;
using BattleShip.DataAccess.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BattleShip.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200720093702_AddStatistics")]
    partial class AddStatistics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        
            modelBuilder.Entity("BattleShip.Models.Entities.StatisticsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MoveCount")
                        .HasColumnType("int");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatisticsRecords");
                });

            modelBuilder.Entity("BattleShip.Models.Entities.WinnerShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InjuredCells")
                        .HasColumnType("int");

                    b.Property<int>("StatisticsRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatisticsRecordId");

                    b.ToTable("WinnerShips");
                });       
            
            modelBuilder.Entity("BattleShip.Models.Entities.WinnerShip", b =>
                {
                    b.HasOne("BattleShip.Models.Entities.StatisticsRecord", "StatisticsRecord")
                        .WithMany("WinnerShips")
                        .HasForeignKey("StatisticsRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

        
#pragma warning restore 612, 618
        }
    }
}
